  - name: add public key for certbot repo
    shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8C47BE8E75BCA694
    become: yes

  - name: add repository for certbot
    apt_repository:
      repo: deb http://ppa.launchpad.net/certbot/certbot/ubuntu bionic main
      state: present
    become: "yes"
   



  - name: Install base packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
        - python-certbot-nginx
    become: "yes"


  - name: Enable UFW
    ufw:
      state: enabled
    become: "yes"

  - name: Allow OpenSSH
    ufw:
      rule: allow
      name: OpenSSH
    become: "yes"

  - name: Allow Nginx Full
    ufw:
      rule: allow
      name: Nginx Full
    become: "yes"

  - name: stop nginx
    service:
        name: nginx
        state: stopped
    become: "yes"

  - name: Obtain SSL certificate
    command: certbot --nginx --noninteractive --agree-tos --email calvineotieno010@gmail.com -d calvineotienotest.duckdns.org   -d www.calvineotienotest.duckdns.org  
    become: yes

  - name: free port 80
    command: fuser -k 80/tcp
    become: yes

  - name: start nginx
    service:
        name: nginx
        state: restarted
    become: "yes"
